<a href="https://colab.research.google.com/github/SuddhashilSarkar/ML_Lab_Assignments/blob/main/ML_Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Create a Numpy array from the following list: [[1, 2, 3], [4, 5, 6], [7, 8,9]] . Print the values of the array and the shape.

import numpy as np

# Create a Numpy array from the list
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the values of the array
print("Array values:\n", arr)

# Print the shape of the array
print("\nArray shape:", arr.shape)


Array values:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array shape: (3, 3)


In [ ]:
#  Perform the following Numpy operations
# a) Create a Numpy array my_arr filled with all ones with 3 rows and 4 columns.
# b) Add the value 5 to each element of the Numpy array my_arr .
# c) Perform the element-wise logarithm of the Numpy array my_arr .
# d) Compute the mean in arr_mean ,
# e) the standard deviation in arr_std ,
# f) the sum in arr_sum ,
# g) the max value in arr_max ,

import numpy as np


# Create a Numpy array from the list
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the values of the array
print("Array values:\n", arr)

# Print the shape of the array
print("\nArray shape:", arr.shape)

# a) Create a Numpy array filled with all ones
my_arr = np.ones((3, 4))
print("\nArray filled with ones:\n", my_arr)

# b) Add the value 5 to each element of the array
my_arr_plus_5 = my_arr + 5
print("\nArray with 5 added to each element:\n", my_arr_plus_5)

# c) Perform the element-wise logarithm of the array
my_arr_log = np.log(my_arr_plus_5)
print("\nElement-wise logarithm of the array:\n", my_arr_log)

# d) Compute the mean, standard deviation, sum, and max value of the original array
arr_mean = np.mean(arr)
arr_std = np.std(arr)
arr_sum = np.sum(arr)
arr_max = np.max(arr)

print("\nMean of the array:", arr_mean)
print("Standard deviation of the array:", arr_std)
print("Sum of the array:", arr_sum)
print("Max value in the array:", arr_max)


Array values:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Array shape: (3, 3)

Array filled with ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array with 5 added to each element:
 [[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]

Element-wise logarithm of the array:
 [[1.79175947 1.79175947 1.79175947 1.79175947]
 [1.79175947 1.79175947 1.79175947 1.79175947]
 [1.79175947 1.79175947 1.79175947 1.79175947]]

Mean of the array: 5.0
Standard deviation of the array: 2.581988897471611
Sum of the array: 45
Max value in the array: 9


In [ ]:
# h) the index of the max value in arr_max_idx of the array my_arr.
arr_max_idx = np.argmax(my_arr)
print("\nIndex of the max value in my_arr:", arr_max_idx)

# i) Compute the mean along the rows axis in arr_mean_rows of the array my_arr.
arr_mean_rows = np.mean(my_arr, axis=0)
print("\nMean along the rows of my_arr:", arr_mean_rows)



Index of the max value in my_arr: 0

Mean along the rows of my_arr: [1. 1. 1. 1.]


In [ ]:
# Create a Numpy array my_arr filled with all ones with 5 rows and 5 columns.
# a) Assign the value of the element in the fourth row and the second column of the array my_arr into a variable value .
# b) Assign the values of the slice corresponding to the rows from 0 to 2 (both included) and the columns from 1 to 2
#  (both included) into a variable slice_arr

import numpy as np
# Create a Numpy array filled with all ones (5x5)
my_arr = np.ones((5, 5))

# a) Assign the value of the element in the fourth row and second column
value = my_arr[3, 1]
print("Value at (3, 1):", value)

# b) Assign the slice corresponding to rows 0-2 and columns 1-2
slice_arr = my_arr[0:3, 1:3]
print("\nSlice of the array:\n", slice_arr)

# c) Assign the values of the slice with all the columns of the last 3 rows into a variable slice_arr.
slice_arr = my_arr[2:, :]
print("\nSlice of the last 3 rows:\n", slice_arr)

# d) Assign the values of the slice with all the columns of the last 3 rows into a variable slice_arr.
# Then assign to all the elements of slice_arr the value -1
slice_arr = my_arr[2:, :]
slice_arr[:] = -1
print("\nSlice of the last 3 rows with -1 values:\n", slice_arr)


Value at (3, 1): 1.0

Slice of the array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

Slice of the last 3 rows:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Slice of the last 3 rows with -1 values:
 [[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]


In [ ]:
# Create a Numpy array my_arr filled with all ones with 4 rows and 6 columns.
# a) Counts the number of non-zero values in the array
# b) Count the number of elements along a given axis
# c) Trim the leading and/or trailing zeros from a 1-D array
# d) Reverse a numpy array

import numpy as np
# Create a Numpy array filled with all ones (4x6)
my_arr = np.ones((4, 6))

# a) Count non-zero values
non_zero_count = np.count_nonzero(my_arr)
print("Number of non-zero values:", non_zero_count)

# b) Count elements along an axis
count_along_axis_0 = np.count_nonzero(my_arr, axis=0)
print("\nCount along axis 0:", count_along_axis_0)

# c) Trim leading/trailing zeros (example with a 1D array)
arr_1d = np.array([0, 0, 1, 2, 3, 0, 0])
trimmed_arr = np.trim_zeros(arr_1d)
print("\nTrimmed 1D array:", trimmed_arr)

# d) Reverse the array
reversed_arr = np.flip(my_arr)
print("\nReversed array:\n", reversed_arr)

# e) Calculate the sum of the diagonal elements of a NumPy array
diagonal_sum = np.trace(my_arr)
print("\nSum of diagonal elements:", diagonal_sum)

# f) Adding and Subtracting Matrices in Python
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

addition_result = matrix1 + matrix2
subtraction_result = matrix1 - matrix2

print("\nAddition of matrices:\n", addition_result)
print("\nSubtraction of matrices:\n", subtraction_result)

# g) Ways to add row/columns in numpy array
# Adding a row
new_row = np.array([9, 10, 11, 12, 13, 14])
my_arr_with_row = np.vstack((my_arr, new_row))
print("\nArray with added row:\n", my_arr_with_row)

# Adding a column
new_column = np.array([13, 14, 15, 16]).reshape(-1, 1)
my_arr_with_column = np.hstack((my_arr, new_column))
print("\nArray with added column:\n", my_arr_with_column)

# h) Matrix Multiplication in NumPy
matrix3 = np.array([[1, 2], [3, 4]])
matrix4 = np.array([[5, 6], [7, 8]])

multiplication_result = np.dot(matrix3, matrix4)
print("\nMatrix multiplication result:\n", multiplication_result)


Number of non-zero values: 24

Count along axis 0: [4 4 4 4 4 4]

Trimmed 1D array: [1 2 3]

Reversed array:
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

Sum of diagonal elements: 4.0

Addition of matrices:
 [[ 6  8]
 [10 12]]

Subtraction of matrices:
 [[-4 -4]
 [-4 -4]]

Array with added row:
 [[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 9. 10. 11. 12. 13. 14.]]

Array with added column:
 [[ 1.  1.  1.  1.  1.  1. 13.]
 [ 1.  1.  1.  1.  1.  1. 14.]
 [ 1.  1.  1.  1.  1.  1. 15.]
 [ 1.  1.  1.  1.  1.  1. 16.]]

Matrix multiplication result:
 [[19 22]
 [43 50]]


In [ ]:
# Create a Numpy array my_arr filled with all ones with 4 rows and 6 columns.
# a) How to get the indices of the sorted array using NumPy in Python?
# b) Finding the k smallest values of a NumPy array
# c) How to get the n-largest values of an array using NumPy?
# d) Sort the values in a matrix

import numpy as np
# Create a Numpy array filled with all ones (4x6)
my_arr = np.ones((4, 6))

# a) Get indices of sorted array
sorted_indices = np.argsort(my_arr, axis=None)  # Flatten and sort
print("Indices of sorted array:", sorted_indices)

# b) Finding k smallest values (example with k=3)
k = 3
smallest_indices = np.argpartition(my_arr, kth=k, axis=None)[:k]
smallest_values = my_arr.flatten()[smallest_indices]
print("\nSmallest values:", smallest_values)

# c) Get n-largest values (example with n=5)
n = 5
largest_indices = np.argpartition(my_arr, kth=-n, axis=None)[-n:]
largest_values = my_arr.flatten()[largest_indices]
print("\nLargest values:", largest_values)

# d) Sort values in a matrix (along each row)
sorted_matrix = np.sort(my_arr, axis=1)
print("\nSorted matrix (row-wise):\n", sorted_matrix)


Indices of sorted array: [ 0 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1 22 23]

Smallest values: [1. 1. 1.]

Largest values: [1. 1. 1. 1. 1.]

Sorted matrix (row-wise):
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
